[package]

name = "sersve"
version = "0.0.1"
authors = ["Till Hoeppner <till@hoeppner.ws>"]

[[bin]]
name = "sersve"
path = "src/sersve.rs"

[dependencies]
iron = "*"
glob = "*"
conduit-mime-types = "*"
lazy_static = "~0.1.1"

[dependencies.persistent]
git = "https://github.com/iron/persistent"
